# Package             : json-simple
# Source Repo         : https://github.com/fangyidong/json-simple
# Travis Job Link     : 
# Created travis.yml  : Yes
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later

arch:
  - amd64
  - ppc64le
required: sudo
before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y git wget openjdk-8-jdk openjdk-8-jre

language: java

jdk:
  - openjdk11

script:
  - sudo mvn install
  
    
