# Package             : json-simple
# Source Repo         : https://github.com/fangyidong/json-simple
# Travis Job Link     : 
# Created travis.yml  : Yes
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later

arch:
  - amd64
  - ppc64le

language: java

jdk:
  - openjdk8

script:
  - sudo mvn install
  
    
